backend:
  name: gitlab
  app_id: 7298c0fae10f6259245586d5b414693f7e9459d7795af6daee0b5adb7622932d
  repo: itfobos/eastbanctech-website # Path to your GitLab repository
  auth_type: implicit # Required for implicit grant
  branch: epic/EWD-301-cms-demo-data

collections:
  - name: "vacancies" # Used in routes, e.g., /admin/collections/vacancies
    label: "Vacancies" # Used in the UI
    folder: "content/vacancies" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.html
    extension: md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Hidden", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Path: /admin/collections/blog
    label: "Blog"
    folder: "content/technology-insights/blog"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: 'YYYY-MM-DD'
        timeFormat: false
        dateFormat: true
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Cover image", name: "image", widget: "image", allow_multiple: false}
      - {label: "No image", name: "noimage", widget: "boolean", default: true}
      - {label: "Author", name: "author", widget: "string"}
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Meta description", name: "seodescription", widget: "string", required: false}
          - {label: "Page title", name: "pagetitle", widget: "string", required: false}
          - {label: "No index the page", name: "noindexpage", widget: "boolean", default: false}
          - {label: "Canonical URL", name: "canonical", widget: "string", required: false}
      - {label: "Text preview", name: "textpreview", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Type of", name: "typeof", widget: "hidden", default: 'Blog'}

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
